/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { simulateRoutes } from "./simulate.routes.js";
export { placementRoutes } from "./placement.routes.js";
export { rollbackRoutes } from "./rollback.routes.js";
