/**
 * Routes for Placement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getPlacement, listPlacements, requestPlacement } from "../handlers/placement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function placementRoutes(fastify: FastifyInstance) {
  // GET /v1/placements (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/placements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlacementsDependenciesForRequest();
        await listPlacements(request, reply, deps);
      });
    }
  );


  // POST /v1/placements (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/placements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlacementsDependenciesForRequest();
        await requestPlacement(request, reply, deps);
      });
    }
  );


  // GET /v1/placements/{placementId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/placements/:placementId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { placementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlacementsDependenciesForRequest();
        await getPlacement(request, reply, deps);
      });
    }
  );


}
