/**
 * Placement Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PlacementEntity } from "@rimcast/core/placements/models/index.js";
import { placementsSchemas } from "@rimcast/core/placements";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "plc";

export function createPlacement(overrides: Partial<PlacementEntity> = {}) {
  const raw = {
    id: overrides.id ?? `plc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    modelVersionId: overrides.modelVersionId ?? faker.string.uuid(),
    siteId: overrides.siteId ?? faker.string.uuid(),
    status: overrides.status ?? "accepted",
    ...overrides,
  };

  return placementsSchemas.Placement.parse(raw);
}

export function placementBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPlacement(overrides));
}
