/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildCapacityDomainModule,
  buildGovernanceDomainModule,
  buildIdentityDomainModule,
  buildIncidentsDomainModule,
  buildModelsDomainModule,
  buildPlacementsDomainModule,
  buildTelemetryDomainModule,
} from "../domains/index.js";
import type {
  CapacityDomainModule,
  GovernanceDomainModule,
  IdentityDomainModule,
  IncidentsDomainModule,
  ModelsDomainModule,
  PlacementsDomainModule,
  TelemetryDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private capacityModule: CapacityDomainModule | null = null;
  private governanceModule: GovernanceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private incidentsModule: IncidentsDomainModule | null = null;
  private modelsModule: ModelsDomainModule | null = null;
  private placementsModule: PlacementsDomainModule | null = null;
  private telemetryModule: TelemetryDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get capacity domain module
   */
  getCapacityDependencies(): CapacityDomainModule {
    if (!this.capacityModule) {
      this.capacityModule = buildCapacityDomainModule(this.dynamoClient);
    }
    return this.capacityModule;
  }

  /**
   * Get governance domain module
   */
  getGovernanceDependencies(): GovernanceDomainModule {
    if (!this.governanceModule) {
      this.governanceModule = buildGovernanceDomainModule(this.dynamoClient);
    }
    return this.governanceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get incidents domain module
   */
  getIncidentsDependencies(): IncidentsDomainModule {
    if (!this.incidentsModule) {
      this.incidentsModule = buildIncidentsDomainModule(this.dynamoClient);
    }
    return this.incidentsModule;
  }

  /**
   * Get models domain module
   */
  getModelsDependencies(): ModelsDomainModule {
    if (!this.modelsModule) {
      this.modelsModule = buildModelsDomainModule(this.dynamoClient);
    }
    return this.modelsModule;
  }

  /**
   * Get placements domain module
   */
  getPlacementsDependencies(): PlacementsDomainModule {
    if (!this.placementsModule) {
      this.placementsModule = buildPlacementsDomainModule(this.dynamoClient);
    }
    return this.placementsModule;
  }

  /**
   * Get telemetry domain module
   */
  getTelemetryDependencies(): TelemetryDomainModule {
    if (!this.telemetryModule) {
      this.telemetryModule = buildTelemetryDomainModule(this.dynamoClient);
    }
    return this.telemetryModule;
  }

  clearCapacityDependencies(): void { this.capacityModule = null; }
  clearGovernanceDependencies(): void { this.governanceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearIncidentsDependencies(): void { this.incidentsModule = null; }
  clearModelsDependencies(): void { this.modelsModule = null; }
  clearPlacementsDependencies(): void { this.placementsModule = null; }
  clearTelemetryDependencies(): void { this.telemetryModule = null; }

  getCapacityDependenciesForRequest(): CapacityDomainModule {
    return this.getCapacityDependencies();
  }

  getGovernanceDependenciesForRequest(): GovernanceDomainModule {
    return this.getGovernanceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getIncidentsDependenciesForRequest(): IncidentsDomainModule {
    return this.getIncidentsDependencies();
  }

  getModelsDependenciesForRequest(): ModelsDomainModule {
    return this.getModelsDependencies();
  }

  getPlacementsDependenciesForRequest(): PlacementsDomainModule {
    return this.getPlacementsDependencies();
  }

  getTelemetryDependenciesForRequest(): TelemetryDomainModule {
    return this.getTelemetryDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.capacityModule = null;
    this.governanceModule = null;
    this.identityModule = null;
    this.incidentsModule = null;
    this.modelsModule = null;
    this.placementsModule = null;
    this.telemetryModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
