/**
 * Models DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Models Domain Module - Composition root
 *
 * DDD: Composition root for models domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  LatencyBudgetRepositoryAdapter,
  VModelRepositoryAdapter,
} from "@rimcast/adapters/models";
import { getIdGeneratorService } from "@rimcast/adapters";
import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetModelVersion,
  ExecuteListModelVersions,
  ExecuteRegisterModelVersion,
  ExecuteSetLatencyBudget,
} from "@rimcast/services/models/usecases";
// Ports (interfaces)
import type {
  LatencyBudgetRepository,
  VModelRepository,
} from "@rimcast/services/models/ports";

export interface ModelsDomainModule {
  repos: {
    latencyBudgets: LatencyBudgetRepository;
    vModels: VModelRepository;
  };
  useCases: {
    latencyBudgets: {
      update: ExecuteSetLatencyBudget;
    };
    vModels: {
      create: ExecuteRegisterModelVersion;
      get: ExecuteGetModelVersion;
      list: ExecuteListModelVersions;
    };
  };
}

export function buildModelsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ModelsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      latencyBudgets?: LatencyBudgetRepository;
      vModels?: VModelRepository;
    } = {};

    obj.latencyBudgets = new LatencyBudgetRepositoryAdapter(dynamoClient);
    obj.vModels = new VModelRepositoryAdapter(dynamoClient);
    return {
      latencyBudgets: obj.latencyBudgets!,
      vModels: obj.vModels!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    latencyBudgets: {
      update: new ExecuteSetLatencyBudget(executionContext, idGenerator, repos.latencyBudgets),
    },
    vModels: {
      create: new ExecuteRegisterModelVersion(executionContext, idGenerator, repos.vModels),
      get: new ExecuteGetModelVersion(executionContext, idGenerator, repos.vModels),
      list: new ExecuteListModelVersions(executionContext, idGenerator, repos.vModels),
    },
  };
  return { repos, useCases: useCases as ModelsDomainModule["useCases"] };
}
