/**
 * LatencyBudget Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/models.openapi.types.js";
import { schemas } from "../schemas/models.schemas.js";

/**
 * Entity: LatencyBudgetEntity
 * Description: Represents the LatencyBudget domain model.
 * Source: schemas.LatencyBudget
 * Type: Domain Entity (API)
 */
export const LatencyBudgetEntitySchema = schemas.LatencyBudget;
export type LatencyBudgetEntity = components["schemas"]["LatencyBudget"];
