/**
 * Incidents DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Incidents Domain Module - Composition root
 *
 * DDD: Composition root for incidents domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  IncidentRepositoryAdapter,
} from "@rimcast/adapters/incidents";
import { getIdGeneratorService } from "@rimcast/adapters";
import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateIncidentPack,
  ExecuteGetIncidentPack,
  ExecuteListIncidentPacks,
} from "@rimcast/services/incidents/usecases";
// Ports (interfaces)
import type {
  IncidentRepository,
} from "@rimcast/services/incidents/ports";

export interface IncidentsDomainModule {
  repos: {
    incidents: IncidentRepository;
  };
  useCases: {
    incidents: {
      create: ExecuteCreateIncidentPack;
      get: ExecuteGetIncidentPack;
      list: ExecuteListIncidentPacks;
    };
  };
}

export function buildIncidentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): IncidentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      incidents?: IncidentRepository;
    } = {};

    obj.incidents = new IncidentRepositoryAdapter(dynamoClient);
    return {
      incidents: obj.incidents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    incidents: {
      create: new ExecuteCreateIncidentPack(executionContext, idGenerator, repos.incidents),
      get: new ExecuteGetIncidentPack(executionContext, idGenerator, repos.incidents),
      list: new ExecuteListIncidentPacks(executionContext, idGenerator, repos.incidents),
    },
  };
  return { repos, useCases: useCases as IncidentsDomainModule["useCases"] };
}
