/**
 * Repository interface for EgressPolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EgressPolicyEntity
} from "../models/egress-policy.entity.js";
import type {
  UpsertEgressPolicyRequestInput
} from "../types/index.js";
/**
 * EgressPolicyRepository Interface
 */
export interface EgressPolicyRepository extends UpdateReadRepository<EgressPolicyEntity, UpsertEgressPolicyRequestInput, string, Record<string, never>> {

}
