/**
 * Repository interface for OverflowException
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  OverflowExceptionEntity
} from "../models/overflow-exception.entity.js";
import type {
  ListOverflowExceptionsParams,
  OverflowException
} from "../types/index.js";
/**
 * OverflowExceptionRepository Interface
 */
export interface OverflowExceptionRepository extends CreateReadRepository<OverflowExceptionEntity, OverflowException, string, ListOverflowExceptionsParams> {

}
