/**
 * Repository interface for SiteFreeze
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SiteFreezeEntity
} from "../models/site-freeze.entity.js";
import type {
  ListSiteFreezesParams,
  SiteFreeze
} from "../types/index.js";
/**
 * SiteFreezeRepository Interface
 */
export interface SiteFreezeRepository extends CreateReadRepository<SiteFreezeEntity, SiteFreeze, string, ListSiteFreezesParams> {

}
