/**
 * LatencyBudget DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LatencyBudget DTOs
 *
 * DDD: Application DTOs for LatencyBudget use cases.
 */

import type { SetLatencyBudgetParams, SetLatencyBudgetRequestInput } from "@rimcast/core/models/types";

export type SetLatencyBudgetInput = SetLatencyBudgetParams & SetLatencyBudgetRequestInput;

export type SetLatencyBudgetOutput = {};
