/**
 * VModel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModel DTOs
 *
 * DDD: Application DTOs for VModel use cases.
 */

import type { GetModelVersionParams, ListModelVersionsParams, RegisterModelVersionRequestInput } from "@rimcast/core/models/types";

export type ListModelVersionsInput = ListModelVersionsParams;

export type RegisterModelVersionInput = RegisterModelVersionRequestInput;

export type GetModelVersionInput = GetModelVersionParams;

export type ListModelVersionsOutput = {};

export type RegisterModelVersionOutput = {};

export type GetModelVersionOutput = {};
