/**
 * ExecuteGetIncidentPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetIncidentPack Use Case
 *
 * DDD: Application use case for get Incident.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetIncidentPackInput, GetIncidentPackOutput } from "../dto/incident.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { IncidentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetIncidentPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly incident: IncidentRepository
  ) {}

  async execute(input: GetIncidentPackInput): Promise<GetIncidentPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).incidentId) {
      throw new ValidationError("incidentId is required");
    }
    const incidentId = (input as any).incidentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.incident.getIncidentPack({ incidentId: incidentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${incidentId}`);
    }

    return entity as GetIncidentPackOutput;
  }
}
