/**
 * SlaSample DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlaSample DTOs
 *
 * DDD: Application DTOs for SlaSample use cases.
 */

import type { IngestSlaSampleRequestInput, ListSlaSamplesParams } from "@rimcast/core/telemetry/types";

export type ListSlaSamplesInput = ListSlaSamplesParams;

export type IngestSlaSampleInput = IngestSlaSampleRequestInput;

export type ListSlaSamplesOutput = {};

export type IngestSlaSampleOutput = {};
