/**
 * ListSafeMode DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSafeModeEventsParams } from "@rimcast/core/governance";

export function createListSafeModeRequest(overrides: Partial<ListSafeModeEventsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
