/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as capacityRoutes from "../../domains/capacity/routes/index.js";
import * as governanceRoutes from "../../domains/governance/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as incidentsRoutes from "../../domains/incidents/routes/index.js";
import * as modelsRoutes from "../../domains/models/routes/index.js";
import * as placementsRoutes from "../../domains/placements/routes/index.js";
import * as telemetryRoutes from "../../domains/telemetry/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "capacity", mod: capacityRoutes },
  { domain: "governance", mod: governanceRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "incidents", mod: incidentsRoutes },
  { domain: "models", mod: modelsRoutes },
  { domain: "placements", mod: placementsRoutes },
  { domain: "telemetry", mod: telemetryRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
