/**
 * EgressPolicy Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/governance.openapi.types.js";
import { schemas } from "../schemas/governance.schemas.js";

/**
 * Entity: EgressPolicyEntity
 * Description: Represents the EgressPolicy domain model.
 * Source: schemas.EgressPolicy
 * Type: Domain Entity (API)
 */
export const EgressPolicyEntitySchema = schemas.EgressPolicy;
export type EgressPolicyEntity = components["schemas"]["EgressPolicy"];
