/**
 * OverflowException Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/governance.openapi.types.js";
import { schemas } from "../schemas/governance.schemas.js";

/**
 * Entity: OverflowExceptionEntity
 * Description: Represents the OverflowException domain model.
 * Source: schemas.OverflowException
 * Type: Domain Entity (API)
 */
export const OverflowExceptionEntitySchema = schemas.OverflowException;
export type OverflowExceptionEntity = components["schemas"]["OverflowException"];
