/**
 * ExecuteGetPlacement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPlacement Use Case
 *
 * DDD: Application use case for get Placement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPlacementInput, GetPlacementOutput } from "../dto/placement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { PlacementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPlacement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly placement: PlacementRepository
  ) {}

  async execute(input: GetPlacementInput): Promise<GetPlacementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.plcId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).placementId) {
      throw new ValidationError("placementId is required");
    }
    const placementId = (input as any).placementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.placement.getPlacement({ placementId: placementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${placementId}`);
    }

    return entity as GetPlacementOutput;
  }
}
