/**
 * ExecuteListPlacements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPlacements Use Case
 *
 * DDD: Application use case for list Placement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPlacementsInput, ListPlacementsOutput } from "../dto/placement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { PlacementRepository } from "../ports";

export class ExecuteListPlacements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly placement: PlacementRepository
  ) {}

  async execute(input: ListPlacementsInput): Promise<ListPlacementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.plcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.placement.listPlacements({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPlacementsOutput;
  }
}
