/**
 * ExecuteRequestPlacement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestPlacement Use Case
 *
 * DDD: Application use case for get Placement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestPlacementInput, RequestPlacementOutput } from "../dto/placement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { PlacementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRequestPlacement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly placement: PlacementRepository
  ) {}

  async execute(input: RequestPlacementInput): Promise<RequestPlacementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.plcId();

    // All field names extracted from OpenAPI spec: allowCloudOverflow, modelVersionId, preferredDeviceClass, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelVersionId) {
      throw new ValidationError("modelVersionId is required");
    }
    const modelversionId = (input as any).modelVersionId;

    // Pass full request body + correlation/org context for placement decisioning
    const entity = await this.placement.requestPlacement({
      ...input,
      modelVersionId: modelversionId,
      orgId: this.context.getOrgId(),
      correlationId,
    } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelversionId}`);
    }

    return entity as RequestPlacementOutput;
  }
}
