/**
 * ExecuteSimulatePlacementFeasibility - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSimulatePlacementFeasibility Use Case
 *
 * DDD: Application use case for get Simulate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SimulatePlacementFeasibilityInput, SimulatePlacementFeasibilityOutput } from "../dto/simulate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { SimulateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSimulatePlacementFeasibility {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly simulate: SimulateRepository
  ) {}

  async execute(input: SimulatePlacementFeasibilityInput): Promise<SimulatePlacementFeasibilityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.plcId();

    // All field names extracted from OpenAPI spec: modelVersionId, preferredDeviceClass, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelVersionId) {
      throw new ValidationError("modelVersionId is required");
    }
    const modelversionId = (input as any).modelVersionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.simulate.simulatePlacementFeasibility({ modelVersionId: modelversionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelversionId}`);
    }

    return entity as SimulatePlacementFeasibilityOutput;
  }
}
