/**
 * Placement Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/placements.openapi.types.js";
import { schemas } from "../schemas/placements.schemas.js";

/**
 * Entity: PlacementEntity
 * Description: Represents the Placement domain model.
 * Source: schemas.Placement
 * Type: Domain Entity (API)
 */
export const PlacementEntitySchema = schemas.Placement;
export type PlacementEntity = components["schemas"]["Placement"];
