/**
 * Routes for Node
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listEdgeNodes, publishEdgeNode } from "../handlers/node.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function nodeRoutes(fastify: FastifyInstance) {
  // GET /v1/capacity/nodes (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/capacity/nodes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapacityDependenciesForRequest();
        await listEdgeNodes(request, reply, deps);
      });
    }
  );


  // POST /v1/capacity/nodes (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/capacity/nodes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapacityDependenciesForRequest();
        await publishEdgeNode(request, reply, deps);
      });
    }
  );


}
