/**
 * Routes for Offer
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listCapacityOffers, publishCapacityOffer } from "../handlers/offer.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function offerRoutes(fastify: FastifyInstance) {
  // GET /v1/capacity/offers (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/capacity/offers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapacityDependenciesForRequest();
        await listCapacityOffers(request, reply, deps);
      });
    }
  );


  // POST /v1/capacity/offers (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/capacity/offers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapacityDependenciesForRequest();
        await publishCapacityOffer(request, reply, deps);
      });
    }
  );


}
