/**
 * Routes for Withdraw
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { withdrawCapacityOffer } from "../handlers/withdraw.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function withdrawRoutes(fastify: FastifyInstance) {
  // POST /v1/capacity/offers/{offerId}/withdraw (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/capacity/offers/:offerId/withdraw",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapacityDependenciesForRequest();
        await withdrawCapacityOffer(request, reply, deps);
      });
    }
  );


}
