/**
 * Clear DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Clear DTOs
 *
 * DDD: Application DTOs for Clear use cases.
 */

import type { ClearSafeModeParams, ClearSafeModeRequestInput } from "@rimcast/core/governance/types";

export type ClearSafeModeInput = ClearSafeModeParams & ClearSafeModeRequestInput;

export type ClearSafeModeOutput = {};
