/**
 * OverflowException DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverflowException DTOs
 *
 * DDD: Application DTOs for OverflowException use cases.
 */

import type { ListOverflowExceptionsParams, RequestOverflowExceptionRequestInput } from "@rimcast/core/governance/types";

export type ListOverflowExceptionsInput = ListOverflowExceptionsParams;

export type RequestOverflowExceptionInput = RequestOverflowExceptionRequestInput;

export type ListOverflowExceptionsOutput = {};

export type RequestOverflowExceptionOutput = {};
