/**
 * SafeMode DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SafeMode DTOs
 *
 * DDD: Application DTOs for SafeMode use cases.
 */

import type { EnterSafeModeRequestInput, ListSafeModeEventsParams } from "@rimcast/core/governance/types";

export type ListSafeModeEventsInput = ListSafeModeEventsParams;

export type EnterSafeModeInput = EnterSafeModeRequestInput;

export type ListSafeModeEventsOutput = {};

export type EnterSafeModeOutput = {};
