/**
 * SiteFreeze DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SiteFreeze DTOs
 *
 * DDD: Application DTOs for SiteFreeze use cases.
 */

import type { FreezeSitePlacementsRequestInput, ListSiteFreezesParams } from "@rimcast/core/governance/types";

export type ListSiteFreezesInput = ListSiteFreezesParams;

export type FreezeSitePlacementsInput = FreezeSitePlacementsRequestInput;

export type ListSiteFreezesOutput = {};

export type FreezeSitePlacementsOutput = {};
