/**
 * Unfreeze DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Unfreeze DTOs
 *
 * DDD: Application DTOs for Unfreeze use cases.
 */

import type { UnfreezeSitePlacementsParams } from "@rimcast/core/governance/types";

export type UnfreezeSitePlacementsInput = UnfreezeSitePlacementsParams;

export type UnfreezeSitePlacementsOutput = {};
