/**
 * PlacementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlacementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PlacementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PlacementRepository,
} from "@rimcast/services/placements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PlacementRepositoryDdb } from "./placement-repository.ddb.js";

/**
 * PlacementRepositoryAdapter
 *
 * Implements PlacementRepository port for infrastructure layer.
 */
export class PlacementRepositoryAdapter implements PlacementRepository {
  private readonly ddb: PlacementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PlacementRepositoryDdb(this.dynamoClient);
  }

  async listPlacements(input: Parameters<PlacementRepository['listPlacements']>[0]): Promise<Awaited<ReturnType<PlacementRepository['listPlacements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPlacements(input);
  }

  async requestPlacement(input: Parameters<PlacementRepository['requestPlacement']>[0]): Promise<Awaited<ReturnType<PlacementRepository['requestPlacement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestPlacement(input);
  }

  async getPlacement(input: Parameters<PlacementRepository['getPlacement']>[0]): Promise<Awaited<ReturnType<PlacementRepository['getPlacement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPlacement(input);
  }
}
