/**
 * Repository interface for Placement
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PlacementEntity
} from "../models/placement.entity.js";
import type {
  ListPlacementsParams,
  Placement
} from "../types/index.js";
/**
 * PlacementRepository Interface
 */
export interface PlacementRepository extends CreateReadRepository<PlacementEntity, Placement, string, ListPlacementsParams> {

}
