/**
 * Repository interface for LatencyBudget
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LatencyBudgetEntity
} from "../models/latency-budget.entity.js";
import type {
  SetLatencyBudgetRequestInput
} from "../types/index.js";
/**
 * LatencyBudgetRepository Interface
 */
export interface LatencyBudgetRepository extends UpdateReadRepository<LatencyBudgetEntity, SetLatencyBudgetRequestInput, string, Record<string, never>> {

}
