/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ClearRepositoryAdapter,
  EgressPolicyRepositoryAdapter,
  OverflowExceptionRepositoryAdapter,
  SafeModeRepositoryAdapter,
  SiteFreezeRepositoryAdapter,
  UnfreezeRepositoryAdapter,
} from "@rimcast/adapters/governance";
import { getIdGeneratorService } from "@rimcast/adapters";
import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClearSafeMode,
  ExecuteEnterSafeMode,
  ExecuteFreezeSitePlacements,
  ExecuteListOverflowExceptions,
  ExecuteListSafeModeEvents,
  ExecuteListSiteFreezes,
  ExecuteRequestOverflowException,
  ExecuteUnfreezeSitePlacements,
  ExecuteUpsertEgressPolicy,
} from "@rimcast/services/governance/usecases";
// Ports (interfaces)
import type {
  ClearRepository,
  EgressPolicyRepository,
  OverflowExceptionRepository,
  SafeModeRepository,
  SiteFreezeRepository,
  UnfreezeRepository,
} from "@rimcast/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    clears: ClearRepository;
    egressPolicies: EgressPolicyRepository;
    overflowExceptions: OverflowExceptionRepository;
    safeModes: SafeModeRepository;
    siteFreezes: SiteFreezeRepository;
    unfreezes: UnfreezeRepository;
  };
  useCases: {
    clears: {
      get: ExecuteClearSafeMode;
    };
    egressPolicies: {
      get: ExecuteUpsertEgressPolicy;
    };
    overflowExceptions: {
      get: ExecuteRequestOverflowException;
      list: ExecuteListOverflowExceptions;
    };
    safeModes: {
      get: ExecuteEnterSafeMode;
      list: ExecuteListSafeModeEvents;
    };
    siteFreezes: {
      get: ExecuteFreezeSitePlacements;
      list: ExecuteListSiteFreezes;
    };
    unfreezes: {
      get: ExecuteUnfreezeSitePlacements;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      clears?: ClearRepository;
      egressPolicies?: EgressPolicyRepository;
      overflowExceptions?: OverflowExceptionRepository;
      safeModes?: SafeModeRepository;
      siteFreezes?: SiteFreezeRepository;
      unfreezes?: UnfreezeRepository;
    } = {};

    obj.clears = new ClearRepositoryAdapter(dynamoClient);
    obj.egressPolicies = new EgressPolicyRepositoryAdapter(dynamoClient);
    obj.overflowExceptions = new OverflowExceptionRepositoryAdapter(dynamoClient);
    obj.safeModes = new SafeModeRepositoryAdapter(dynamoClient);
    obj.siteFreezes = new SiteFreezeRepositoryAdapter(dynamoClient);
    obj.unfreezes = new UnfreezeRepositoryAdapter(dynamoClient);
    return {
      clears: obj.clears!,
      egressPolicies: obj.egressPolicies!,
      overflowExceptions: obj.overflowExceptions!,
      safeModes: obj.safeModes!,
      siteFreezes: obj.siteFreezes!,
      unfreezes: obj.unfreezes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    clears: {
      get: new ExecuteClearSafeMode(executionContext, idGenerator, repos.clears),
    },
    egressPolicies: {
      get: new ExecuteUpsertEgressPolicy(executionContext, idGenerator, repos.egressPolicies),
    },
    overflowExceptions: {
      get: new ExecuteRequestOverflowException(executionContext, idGenerator, repos.overflowExceptions),
      list: new ExecuteListOverflowExceptions(executionContext, idGenerator, repos.overflowExceptions),
    },
    safeModes: {
      get: new ExecuteEnterSafeMode(executionContext, idGenerator, repos.safeModes),
      list: new ExecuteListSafeModeEvents(executionContext, idGenerator, repos.safeModes),
    },
    siteFreezes: {
      get: new ExecuteFreezeSitePlacements(executionContext, idGenerator, repos.siteFreezes),
      list: new ExecuteListSiteFreezes(executionContext, idGenerator, repos.siteFreezes),
    },
    unfreezes: {
      get: new ExecuteUnfreezeSitePlacements(executionContext, idGenerator, repos.unfreezes),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
