/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the governance domain.
 * Use these factories in tests to create test data.
 */

export { createCreateUnfreezeRequest } from "./unfreeze/dto/create-unfreeze.dto.factory.js";
export { createEgressPolicy } from "./egress-policy/entity/egress-policy.entity.factory.js";
export { createOverflowException } from "./overflow-exception/entity/overflow-exception.entity.factory.js";
export { createSiteFreeze } from "./site-freeze/entity/site-freeze.entity.factory.js";
