/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @rimcast/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@rimcast/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@rimcast/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@rimcast/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@rimcast/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@rimcast/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _capacity from "./capacity/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _incidents from "./incidents/index.js";
import * as _models from "./models/index.js";
import * as _placements from "./placements/index.js";
import * as _telemetry from "./telemetry/index.js";

// Export as namespaces
export const _shared = __shared;
export const capacity = _capacity;
export const governance = _governance;
export const identity = _identity;
export const incidents = _incidents;
export const models = _models;
export const placements = _placements;
export const telemetry = _telemetry;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@rimcast/core"; activity.types.*
//   - Direct exports: import * from "@rimcast/core/activity/types/index.js"
//   - Direct exports: import * from "@rimcast/core/activity/repositories/index.js"
//   - Direct exports: import * from "@rimcast/core/activity/models/index.js"
//   - Direct exports: import * from "@rimcast/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Capacity Service
export { schemas as CapacitySchemas } from "./capacity/schemas/capacity.schemas.js";

// Governance Service
export { schemas as GovernanceSchemas } from "./governance/schemas/governance.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Incidents Service
export { schemas as IncidentsSchemas } from "./incidents/schemas/incidents.schemas.js";

// Models Service
export { schemas as ModelsSchemas } from "./models/schemas/models.schemas.js";

// Placements Service
export { schemas as PlacementsSchemas } from "./placements/schemas/placements.schemas.js";

// Telemetry Service
export { schemas as TelemetrySchemas } from "./telemetry/schemas/telemetry.schemas.js";

