/**
 * EgressPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EgressPolicyRepository Port
 *
 * DDD: Application port for egresspolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { UpsertEgressPolicyInput, UpsertEgressPolicyOutput } from "../dto/egress-policy.dto";
export interface EgressPolicyRepository {
  upsertEgressPolicy(input: UpsertEgressPolicyInput): Promise<UpsertEgressPolicyOutput>;
}

export type { UpsertEgressPolicyInput, UpsertEgressPolicyOutput } from "../dto/egress-policy.dto";
