/**
 * OverflowExceptionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverflowExceptionRepository Port
 *
 * DDD: Application port for overflowexceptionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListOverflowExceptionsInput, ListOverflowExceptionsOutput, RequestOverflowExceptionInput, RequestOverflowExceptionOutput } from "../dto/overflow-exception.dto";
export interface OverflowExceptionRepository {
  listOverflowExceptions(input: ListOverflowExceptionsInput): Promise<ListOverflowExceptionsOutput>;
  requestOverflowException(input: RequestOverflowExceptionInput): Promise<RequestOverflowExceptionOutput>;
}

export type { ListOverflowExceptionsInput, ListOverflowExceptionsOutput, RequestOverflowExceptionInput, RequestOverflowExceptionOutput } from "../dto/overflow-exception.dto";
