/**
 * SafeModeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SafeModeRepository Port
 *
 * DDD: Application port for safemoderepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { EnterSafeModeInput, EnterSafeModeOutput, ListSafeModeEventsInput, ListSafeModeEventsOutput } from "../dto/safe-mode.dto";
export interface SafeModeRepository {
  listSafeModeEvents(input: ListSafeModeEventsInput): Promise<ListSafeModeEventsOutput>;
  enterSafeMode(input: EnterSafeModeInput): Promise<EnterSafeModeOutput>;
}

export type { EnterSafeModeInput, EnterSafeModeOutput, ListSafeModeEventsInput, ListSafeModeEventsOutput } from "../dto/safe-mode.dto";
