/**
 * SiteFreezeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SiteFreezeRepository Port
 *
 * DDD: Application port for sitefreezerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { FreezeSitePlacementsInput, FreezeSitePlacementsOutput, ListSiteFreezesInput, ListSiteFreezesOutput } from "../dto/site-freeze.dto";
export interface SiteFreezeRepository {
  listSiteFreezes(input: ListSiteFreezesInput): Promise<ListSiteFreezesOutput>;
  freezeSitePlacements(input: FreezeSitePlacementsInput): Promise<FreezeSitePlacementsOutput>;
}

export type { FreezeSitePlacementsInput, FreezeSitePlacementsOutput, ListSiteFreezesInput, ListSiteFreezesOutput } from "../dto/site-freeze.dto";
