/**
 * UnfreezeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UnfreezeRepository Port
 *
 * DDD: Application port for unfreezerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { UnfreezeSitePlacementsInput, UnfreezeSitePlacementsOutput } from "../dto/unfreeze.dto";
export interface UnfreezeRepository {
  unfreezeSitePlacements(input: UnfreezeSitePlacementsInput): Promise<UnfreezeSitePlacementsOutput>;
}

export type { UnfreezeSitePlacementsInput, UnfreezeSitePlacementsOutput } from "../dto/unfreeze.dto";
