/**
 * ExecuteUpsertEgressPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertEgressPolicy Use Case
 *
 * DDD: Application use case for get EgressPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertEgressPolicyInput, UpsertEgressPolicyOutput } from "../dto/egress-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { EgressPolicyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteUpsertEgressPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly egressPolicy: EgressPolicyRepository
  ) {}

  async execute(input: UpsertEgressPolicyInput): Promise<UpsertEgressPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: allowOverflow, purposeTags, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).siteId) {
      throw new ValidationError("siteId is required");
    }
    const siteId = (input as any).siteId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.egressPolicy.upsertEgressPolicy({ siteId: siteId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${siteId}`);
    }

    return entity as UpsertEgressPolicyOutput;
  }
}
