/**
 * ExecuteListOverflowExceptions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListOverflowExceptions Use Case
 *
 * DDD: Application use case for list OverflowException.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListOverflowExceptionsInput, ListOverflowExceptionsOutput } from "../dto/overflow-exception.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { OverflowExceptionRepository } from "../ports";

export class ExecuteListOverflowExceptions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly overflowException: OverflowExceptionRepository
  ) {}

  async execute(input: ListOverflowExceptionsInput): Promise<ListOverflowExceptionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.overflowException.listOverflowExceptions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListOverflowExceptionsOutput;
  }
}
