/**
 * ExecuteEnterSafeMode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteEnterSafeMode Use Case
 *
 * DDD: Application use case for get SafeMode.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { EnterSafeModeInput, EnterSafeModeOutput } from "../dto/safe-mode.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { SafeModeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteEnterSafeMode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly safeMode: SafeModeRepository
  ) {}

  async execute(input: EnterSafeModeInput): Promise<EnterSafeModeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: placementId, playbook, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).placementId) {
      throw new ValidationError("placementId is required");
    }
    const placementId = (input as any).placementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.safeMode.enterSafeMode({ placementId: placementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${placementId}`);
    }

    return entity as EnterSafeModeOutput;
  }
}
