/**
 * ExecuteUnfreezeSitePlacements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUnfreezeSitePlacements Use Case
 *
 * DDD: Application use case for get Unfreeze.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UnfreezeSitePlacementsInput, UnfreezeSitePlacementsOutput } from "../dto/unfreeze.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { UnfreezeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteUnfreezeSitePlacements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly unfreeze: UnfreezeRepository
  ) {}

  async execute(input: UnfreezeSitePlacementsInput): Promise<UnfreezeSitePlacementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).freezeId) {
      throw new ValidationError("freezeId is required");
    }
    const freezeId = (input as any).freezeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.unfreeze.unfreezeSitePlacements({ freezeId: freezeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${freezeId}`);
    }

    return entity as UnfreezeSitePlacementsOutput;
  }
}
