/**
 * ExecuteFreezeSitePlacements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteFreezeSitePlacements Use Case
 *
 * DDD: Application use case for get SiteFreeze.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { FreezeSitePlacementsInput, FreezeSitePlacementsOutput } from "../dto/site-freeze.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { SiteFreezeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteFreezeSitePlacements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly siteFreeze: SiteFreezeRepository
  ) {}

  async execute(input: FreezeSitePlacementsInput): Promise<FreezeSitePlacementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: reason, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).siteId) {
      throw new ValidationError("siteId is required");
    }
    const siteId = (input as any).siteId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.siteFreeze.freezeSitePlacements({ siteId: siteId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${siteId}`);
    }

    return entity as FreezeSitePlacementsOutput;
  }
}
