/**
 * ExecuteListSiteFreezes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSiteFreezes Use Case
 *
 * DDD: Application use case for list SiteFreeze.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSiteFreezesInput, ListSiteFreezesOutput } from "../dto/site-freeze.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { SiteFreezeRepository } from "../ports";

export class ExecuteListSiteFreezes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly siteFreeze: SiteFreezeRepository
  ) {}

  async execute(input: ListSiteFreezesInput): Promise<ListSiteFreezesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.siteFreeze.listSiteFreezes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSiteFreezesOutput;
  }
}
