/**
 * ExecuteClearSafeMode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteClearSafeMode Use Case
 *
 * DDD: Application use case for get Clear.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ClearSafeModeInput, ClearSafeModeOutput } from "../dto/clear.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { ClearRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteClearSafeMode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly clear: ClearRepository
  ) {}

  async execute(input: ClearSafeModeInput): Promise<ClearSafeModeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: acknowledgment
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).eventId) {
      throw new ValidationError("eventId is required");
    }
    const eventId = (input as any).eventId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.clear.clearSafeMode({ eventId: eventId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${eventId}`);
    }

    return entity as ClearSafeModeOutput;
  }
}
