/**
 * LatencyBudgetRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LatencyBudgetRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LatencyBudgetRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LatencyBudgetRepository,
} from "@rimcast/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LatencyBudgetRepositoryDdb } from "./latency-budget-repository.ddb.js";

/**
 * LatencyBudgetRepositoryAdapter
 *
 * Implements LatencyBudgetRepository port for infrastructure layer.
 */
export class LatencyBudgetRepositoryAdapter implements LatencyBudgetRepository {
  private readonly ddb: LatencyBudgetRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LatencyBudgetRepositoryDdb(this.dynamoClient);
  }

  async setLatencyBudget(input: Parameters<LatencyBudgetRepository['setLatencyBudget']>[0]): Promise<Awaited<ReturnType<LatencyBudgetRepository['setLatencyBudget']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setLatencyBudget(input);
  }
}
