/**
 * VModelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VModelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VModelRepository,
} from "@rimcast/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VModelRepositoryDdb } from "./vmodel-repository.ddb.js";

/**
 * VModelRepositoryAdapter
 *
 * Implements VModelRepository port for infrastructure layer.
 */
export class VModelRepositoryAdapter implements VModelRepository {
  private readonly ddb: VModelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VModelRepositoryDdb(this.dynamoClient);
  }

  async listModelVersions(input: Parameters<VModelRepository['listModelVersions']>[0]): Promise<Awaited<ReturnType<VModelRepository['listModelVersions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModelVersions(input);
  }

  async registerModelVersion(input: Parameters<VModelRepository['registerModelVersion']>[0]): Promise<Awaited<ReturnType<VModelRepository['registerModelVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerModelVersion(input);
  }

  async getModelVersion(input: Parameters<VModelRepository['getModelVersion']>[0]): Promise<Awaited<ReturnType<VModelRepository['getModelVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getModelVersion(input);
  }
}
