/**
 * ListNode DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEdgeNodesParams } from "@rimcast/core/capacity";

export function createListNodeRequest(overrides: Partial<ListEdgeNodesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
