/**
 * GetPlacement handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPlacement } from "@rimcast/api-server/domains/placements/handlers";
import type { PlacementsDDDDependencies } from "@rimcast/api-server/domains/placements";
import { createPlacement as createPlacementEntity } from "@rimcast/factories/placements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@rimcast/tests/shared";
import { PLACEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPlacement", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PlacementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PlacementsDDDDependencies>(
      PLACEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPlacementEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPlacement, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { placementId: entity.id };

    await getPlacement(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPlacement.execute).toHaveBeenCalledWith(expect.objectContaining({ placementId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { placementId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPlacement, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPlacement(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
