/**
 * RequestPlacement handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { requestPlacement } from "@rimcast/api-server/domains/placements/handlers";
import type { PlacementsDDDDependencies } from "@rimcast/api-server/domains/placements";
import { createPlacement as createPlacementEntity } from "@rimcast/factories/placements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@rimcast/tests/shared";
import { PLACEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RequestPlacement", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PlacementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PlacementsDDDDependencies>(
      PLACEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createPlacementEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRequestPlacement, "execute").mockResolvedValue(useCaseResult);

    await requestPlacement(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRequestPlacement.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
