/**
 * SlaSample Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SlaSampleEntity } from "@rimcast/core/telemetry/models/index.js";
import { telemetrySchemas } from "@rimcast/core/telemetry";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "tla";

export function createSlaSample(overrides: Partial<SlaSampleEntity> = {}) {
  const raw = {
    id: overrides.id ?? `sla_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    latencyMs: overrides.latencyMs ?? faker.number.int(),
    modelVersionId: overrides.modelVersionId ?? faker.string.uuid(),
    placementId: overrides.placementId ?? faker.string.uuid(),
    sampledAt: overrides.sampledAt ?? new Date().toISOString(),
    siteId: overrides.siteId ?? faker.string.uuid(),
    withinBudget: overrides.withinBudget ?? faker.datatype.boolean(),
    ...overrides,
  };

  return telemetrySchemas.SlaSample.parse(raw);
}

export function slaSampleBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSlaSample(overrides));
}
