/**
 * ListSlaSample DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSlaSamplesParams } from "@rimcast/core/telemetry";

export function createListSlaSampleRequest(overrides: Partial<ListSlaSamplesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
