/**
 * Handlers for Rollback
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PlacementsDomainModule } from "../dependencies/placements-ddd.dependencies.js";
import type { RollbackPlacementInput } from "@rimcast/services/placements";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/placements/{placementId}/rollback
 * Operation: rollbackPlacement
 */
export async function rollbackPlacement(
  request: FastifyRequest<{ Params: { placementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PlacementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RollbackPlacementInput = {
    placementId: request.params.placementId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rollbacks.get.execute(input);
  return reply.code(200).send(result);
}


