/**
 * Telemetry DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Telemetry Domain Module - Composition root
 *
 * DDD: Composition root for telemetry domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  SlaSampleRepositoryAdapter,
} from "@rimcast/adapters/telemetry";
import { getIdGeneratorService } from "@rimcast/adapters";
import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteIngestSlaSample,
  ExecuteListSlaSamples,
} from "@rimcast/services/telemetry/usecases";
// Ports (interfaces)
import type {
  SlaSampleRepository,
} from "@rimcast/services/telemetry/ports";

export interface TelemetryDomainModule {
  repos: {
    slaSamples: SlaSampleRepository;
  };
  useCases: {
    slaSamples: {
      get: ExecuteIngestSlaSample;
      list: ExecuteListSlaSamples;
    };
  };
}

export function buildTelemetryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TelemetryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      slaSamples?: SlaSampleRepository;
    } = {};

    obj.slaSamples = new SlaSampleRepositoryAdapter(dynamoClient);
    return {
      slaSamples: obj.slaSamples!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    slaSamples: {
      get: new ExecuteIngestSlaSample(executionContext, idGenerator, repos.slaSamples),
      list: new ExecuteListSlaSamples(executionContext, idGenerator, repos.slaSamples),
    },
  };
  return { repos, useCases: useCases as TelemetryDomainModule["useCases"] };
}
