/**
 * ExecuteSetLatencyBudget - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSetLatencyBudget Use Case
 *
 * DDD: Application use case for update LatencyBudget.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SetLatencyBudgetInput, SetLatencyBudgetOutput } from "../dto/latency-budget.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { LatencyBudgetRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteSetLatencyBudget {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly latencyBudget: LatencyBudgetRepository
  ) {}

  async execute(input: SetLatencyBudgetInput): Promise<SetLatencyBudgetOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelVersionId) {
      throw new ValidationError("modelVersionId is required");
    }
    const modelversionId = (input as any).modelVersionId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.latencyBudget.setLatencyBudget({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as SetLatencyBudgetOutput;
  }
}
