/**
 * ExecuteListSlaSamples - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSlaSamples Use Case
 *
 * DDD: Application use case for list SlaSample.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSlaSamplesInput, ListSlaSamplesOutput } from "../dto/sla-sample.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { SlaSampleRepository } from "../ports";

export class ExecuteListSlaSamples {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly slaSample: SlaSampleRepository
  ) {}

  async execute(input: ListSlaSamplesInput): Promise<ListSlaSamplesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tlaId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.slaSample.listSlaSamples({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSlaSamplesOutput;
  }
}
