/**
 * PlacementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlacementRepository Port
 *
 * DDD: Application port for placementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPlacementInput, GetPlacementOutput, ListPlacementsInput, ListPlacementsOutput, RequestPlacementInput, RequestPlacementOutput } from "../dto/placement.dto";
export interface PlacementRepository {
  listPlacements(input: ListPlacementsInput): Promise<ListPlacementsOutput>;
  requestPlacement(input: RequestPlacementInput): Promise<RequestPlacementOutput>;
  getPlacement(input: GetPlacementInput): Promise<GetPlacementOutput>;
}

export type { GetPlacementInput, GetPlacementOutput, ListPlacementsInput, ListPlacementsOutput, RequestPlacementInput, RequestPlacementOutput } from "../dto/placement.dto";
