/**
 * SlaSample Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/telemetry.openapi.types.js";
import { schemas } from "../schemas/telemetry.schemas.js";

/**
 * Entity: SlaSampleEntity
 * Description: Represents the SlaSample domain model.
 * Source: schemas.SlaSample
 * Type: Domain Entity (API)
 */
export const SlaSampleEntitySchema = schemas.SlaSample;
export type SlaSampleEntity = components["schemas"]["SlaSample"];
