/**
 * IncidentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncidentRepository Port
 *
 * DDD: Application port for incidentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateIncidentPackInput, CreateIncidentPackOutput, GetIncidentPackInput, GetIncidentPackOutput, ListIncidentPacksInput, ListIncidentPacksOutput } from "../dto/incident.dto";
export interface IncidentRepository {
  listIncidentPacks(input: ListIncidentPacksInput): Promise<ListIncidentPacksOutput>;
  createIncidentPack(input: CreateIncidentPackInput): Promise<CreateIncidentPackOutput>;
  getIncidentPack(input: GetIncidentPackInput): Promise<GetIncidentPackOutput>;
}

export type { CreateIncidentPackInput, CreateIncidentPackOutput, GetIncidentPackInput, GetIncidentPackOutput, ListIncidentPacksInput, ListIncidentPacksOutput } from "../dto/incident.dto";
