/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Placements Domain Use Cases
 * 
 * List of all use case names for the placements domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PLACEMENTS_USE_CASES = [
  "executeGetPlacement",
  "executeListPlacements",
  "executeRequestPlacement",
  "executeRollbackPlacement",
  "executeSimulatePlacementFeasibility"
] as const;
