/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildCapacityDomainModule } from "./capacity/dependencies/capacity-ddd.dependencies.js";
export { buildGovernanceDomainModule } from "./governance/dependencies/governance-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildIncidentsDomainModule } from "./incidents/dependencies/incidents-ddd.dependencies.js";
export { buildModelsDomainModule } from "./models/dependencies/models-ddd.dependencies.js";
export { buildPlacementsDomainModule } from "./placements/dependencies/placements-ddd.dependencies.js";
export { buildTelemetryDomainModule } from "./telemetry/dependencies/telemetry-ddd.dependencies.js";

// Export all domain dependency types
export type { CapacityDomainModule } from "./capacity/dependencies/capacity-ddd.dependencies.js";
export type { GovernanceDomainModule } from "./governance/dependencies/governance-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { IncidentsDomainModule } from "./incidents/dependencies/incidents-ddd.dependencies.js";
export type { ModelsDomainModule } from "./models/dependencies/models-ddd.dependencies.js";
export type { PlacementsDomainModule } from "./placements/dependencies/placements-ddd.dependencies.js";
export type { TelemetryDomainModule } from "./telemetry/dependencies/telemetry-ddd.dependencies.js";
