/**
 * NodePublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NodePublisher Port
 *
 * DDD: Application port for nodepublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishEdgeNodeInput, PublishEdgeNodeOutput } from "../dto/node.dto";
export interface NodePublisher {
  publishEdgeNode(input: PublishEdgeNodeInput): Promise<PublishEdgeNodeOutput>;
}

export type { PublishEdgeNodeInput, PublishEdgeNodeOutput } from "../dto/node.dto";
