/**
 * OfferPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OfferPublisher Port
 *
 * DDD: Application port for offerpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishCapacityOfferInput, PublishCapacityOfferOutput } from "../dto/offer.dto";
export interface OfferPublisher {
  publishCapacityOffer(input: PublishCapacityOfferInput): Promise<PublishCapacityOfferOutput>;
}

export type { PublishCapacityOfferInput, PublishCapacityOfferOutput } from "../dto/offer.dto";
