/**
 * SlaSampleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlaSampleRepository Port
 *
 * DDD: Application port for slasamplerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestSlaSampleInput, IngestSlaSampleOutput, ListSlaSamplesInput, ListSlaSamplesOutput } from "../dto/sla-sample.dto";
export interface SlaSampleRepository {
  listSlaSamples(input: ListSlaSamplesInput): Promise<ListSlaSamplesOutput>;
  ingestSlaSample(input: IngestSlaSampleInput): Promise<IngestSlaSampleOutput>;
}

export type { IngestSlaSampleInput, IngestSlaSampleOutput, ListSlaSamplesInput, ListSlaSamplesOutput } from "../dto/sla-sample.dto";
