/**
 * LatencyBudgetRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LatencyBudgetRepository Port
 *
 * DDD: Application port for latencybudgetrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SetLatencyBudgetInput, SetLatencyBudgetOutput } from "../dto/latency-budget.dto";
export interface LatencyBudgetRepository {
  setLatencyBudget(input: SetLatencyBudgetInput): Promise<SetLatencyBudgetOutput>;
}

export type { SetLatencyBudgetInput, SetLatencyBudgetOutput } from "../dto/latency-budget.dto";
