/**
 * VModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepository Port
 *
 * DDD: Application port for vmodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetModelVersionInput, GetModelVersionOutput, ListModelVersionsInput, ListModelVersionsOutput, RegisterModelVersionInput, RegisterModelVersionOutput } from "../dto/vmodel.dto";
export interface VModelRepository {
  listModelVersions(input: ListModelVersionsInput): Promise<ListModelVersionsOutput>;
  registerModelVersion(input: RegisterModelVersionInput): Promise<RegisterModelVersionOutput>;
  getModelVersion(input: GetModelVersionInput): Promise<GetModelVersionOutput>;
}

export type { GetModelVersionInput, GetModelVersionOutput, ListModelVersionsInput, ListModelVersionsOutput, RegisterModelVersionInput, RegisterModelVersionOutput } from "../dto/vmodel.dto";
