/**
 * Node DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Node DTOs
 *
 * DDD: Application DTOs for Node use cases.
 */

import type { ListEdgeNodesParams, PublishEdgeNodeRequestInput } from "@rimcast/core/capacity/types";

export type ListEdgeNodesInput = ListEdgeNodesParams;

export type PublishEdgeNodeInput = PublishEdgeNodeRequestInput;

export type ListEdgeNodesOutput = {};

export type PublishEdgeNodeOutput = {};
