/**
 * Offer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Offer DTOs
 *
 * DDD: Application DTOs for Offer use cases.
 */

import type { ListCapacityOffersParams, PublishCapacityOfferRequestInput } from "@rimcast/core/capacity/types";

export type ListCapacityOffersInput = ListCapacityOffersParams;

export type PublishCapacityOfferInput = PublishCapacityOfferRequestInput;

export type ListCapacityOffersOutput = {};

export type PublishCapacityOfferOutput = {};
