/**
 * Withdraw DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Withdraw DTOs
 *
 * DDD: Application DTOs for Withdraw use cases.
 */

import type { WithdrawCapacityOfferParams } from "@rimcast/core/capacity/types";

export type WithdrawCapacityOfferInput = WithdrawCapacityOfferParams;

export type WithdrawCapacityOfferOutput = {};
