/**
 * SlaSampleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlaSampleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SlaSampleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SlaSampleRepository,
} from "@rimcast/services/telemetry";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SlaSampleRepositoryDdb } from "./sla-sample-repository.ddb.js";

/**
 * SlaSampleRepositoryAdapter
 *
 * Implements SlaSampleRepository port for infrastructure layer.
 */
export class SlaSampleRepositoryAdapter implements SlaSampleRepository {
  private readonly ddb: SlaSampleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SlaSampleRepositoryDdb(this.dynamoClient);
  }

  async listSlaSamples(input: Parameters<SlaSampleRepository['listSlaSamples']>[0]): Promise<Awaited<ReturnType<SlaSampleRepository['listSlaSamples']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSlaSamples(input);
  }

  async ingestSlaSample(input: Parameters<SlaSampleRepository['ingestSlaSample']>[0]): Promise<Awaited<ReturnType<SlaSampleRepository['ingestSlaSample']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestSlaSample(input);
  }
}
