/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@rimcast/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@rimcast/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@rimcast/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _capacity from "./capacity/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _incidents from "./incidents/index.js";
import * as _models from "./models/index.js";
import * as _placements from "./placements/index.js";
import * as _telemetry from "./telemetry/index.js";

// Export as namespaces
export const capacity = _capacity;
export const governance = _governance;
export const identity = _identity;
export const incidents = _incidents;
export const models = _models;
export const placements = _placements;
export const telemetry = _telemetry;
