/**
 * Handlers for Clear
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { ClearSafeModeInput } from "@rimcast/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/governance/safe-mode/{eventId}/clear
 * Operation: clearSafeMode
 */
export async function clearSafeMode(
  request: FastifyRequest<{ Params: { eventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ClearSafeModeInput = {
    eventId: request.params.eventId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.clears.get.execute(input);
  return reply.code(200).send(result);
}


