/**
 * Handlers for EgressPolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { UpsertEgressPolicyInput } from "@rimcast/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v1/governance/egress-policies
 * Operation: upsertEgressPolicy
 */
export async function upsertEgressPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertEgressPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.egressPolicies.get.execute(input);
  return reply.code(200).send(result);
}


