/**
 * Handlers for Unfreeze
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { UnfreezeSitePlacementsInput } from "@rimcast/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/governance/site-freezes/{freezeId}/unfreeze
 * Operation: unfreezeSitePlacements
 */
export async function unfreezeSitePlacements(
  request: FastifyRequest<{ Params: { freezeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UnfreezeSitePlacementsInput = {
    freezeId: request.params.freezeId,
  };
  const result = await deps.useCases.unfreezes.get.execute(input);
  return reply.code(200).send(result);
}


