/**
 * Handlers for Offer
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CapacityDomainModule } from "../dependencies/capacity-ddd.dependencies.js";
import type { ListCapacityOffersInput, PublishCapacityOfferInput } from "@rimcast/services/capacity";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/capacity/offers
 * Operation: listCapacityOffers
 */
export async function listCapacityOffers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], siteId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CapacityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCapacityOffersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.offers.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/capacity/offers
 * Operation: publishCapacityOffer
 */
export async function publishCapacityOffer(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CapacityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishCapacityOfferInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.offers.get.execute(input);
  return reply.code(201).send(result);
}


