/**
 * Handlers for Withdraw
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CapacityDomainModule } from "../dependencies/capacity-ddd.dependencies.js";
import type { WithdrawCapacityOfferInput } from "@rimcast/services/capacity";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/capacity/offers/{offerId}/withdraw
 * Operation: withdrawCapacityOffer
 */
export async function withdrawCapacityOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CapacityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: WithdrawCapacityOfferInput = {
    offerId: request.params.offerId,
  };
  const result = await deps.useCases.withdraws.get.execute(input);
  return reply.code(200).send(result);
}


