/**
 * Repository interface for SlaSample
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SlaSampleEntity
} from "../models/sla-sample.entity.js";
import type {
  ListSlaSamplesParams,
  SlaSample
} from "../types/index.js";
/**
 * SlaSampleRepository Interface
 */
export interface SlaSampleRepository extends CreateReadRepository<SlaSampleEntity, SlaSample, string, ListSlaSamplesParams> {

}
