/**
 * Routes for SafeMode
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { enterSafeMode, listSafeModeEvents } from "../handlers/safe-mode.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function safeModeRoutes(fastify: FastifyInstance) {
  // POST /v1/governance/safe-mode (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/governance/safe-mode",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await enterSafeMode(request, reply, deps);
      });
    }
  );


  // GET /v1/governance/safe-mode (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/governance/safe-mode",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await listSafeModeEvents(request, reply, deps);
      });
    }
  );


}
