/**
 * ExecuteListEdgeNodes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEdgeNodes Use Case
 *
 * DDD: Application use case for list Node.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEdgeNodesInput, ListEdgeNodesOutput } from "../dto/node.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { NodeRepository } from "../ports";

export class ExecuteListEdgeNodes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly node: NodeRepository
  ) {}

  async execute(input: ListEdgeNodesInput): Promise<ListEdgeNodesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.capId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.node.listEdgeNodes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEdgeNodesOutput;
  }
}
