/**
 * ExecutePublishEdgeNode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishEdgeNode Use Case
 *
 * DDD: Application use case for get Node.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishEdgeNodeInput, PublishEdgeNodeOutput } from "../dto/node.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { NodePublisher, NodeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePublishEdgeNode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly nodeRepository: NodeRepository,
    private readonly nodePublisher: NodePublisher
  ) {}

  async execute(input: PublishEdgeNodeInput): Promise<PublishEdgeNodeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.capId();

    // All field names extracted from OpenAPI spec: availableComputeUnits, deviceClass, measuredRttMs, pricePerCompliantInference, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).siteId) {
      throw new ValidationError("siteId is required");
    }
    const siteId = (input as any).siteId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.nodePublisher.publishEdgeNode({ ...(input as any), siteId: siteId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${siteId}`);
    }

    return entity as PublishEdgeNodeOutput;
  }
}
