/**
 * ExecutePublishCapacityOffer - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishCapacityOffer Use Case
 *
 * DDD: Application use case for get Offer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishCapacityOfferInput, PublishCapacityOfferOutput } from "../dto/offer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@rimcast/services/_shared/index.js";
import type { OfferPublisher, OfferRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePublishCapacityOffer {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly offerRepository: OfferRepository,
    private readonly offerPublisher: OfferPublisher
  ) {}

  async execute(input: PublishCapacityOfferInput): Promise<PublishCapacityOfferOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.capId();

    // All field names extracted from OpenAPI spec: edgeNodeId, pricingModel, slotsAvailable, unitPrice
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).edgeNodeId) {
      throw new ValidationError("edgeNodeId is required");
    }
    const edgenodeId = (input as any).edgeNodeId;

    // Publish = create in sandbox; forward full offer payload
    const entity = await this.offerPublisher.publishCapacityOffer({
      ...input,
      edgeNodeId: edgenodeId,
      orgId: this.context.getOrgId(),
      correlationId,
    } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${edgenodeId}`);
    }

    return entity as PublishCapacityOfferOutput;
  }
}
