/**
 * IngestSlaSample handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { ingestSlaSample } from "@rimcast/api-server/domains/telemetry/handlers";
import type { TelemetryDDDDependencies } from "@rimcast/api-server/domains/telemetry";
import { createSlaSample as createSlaSampleEntity } from "@rimcast/factories/telemetry";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@rimcast/tests/shared";
import { TELEMETRY_USE_CASES } from "../__factories__/use-cases.js";

describe("IngestSlaSample", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TelemetryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TelemetryDDDDependencies>(
      TELEMETRY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createSlaSampleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeIngestSlaSample, "execute").mockResolvedValue(useCaseResult);

    await ingestSlaSample(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeIngestSlaSample.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
