/**
 * ListSlaSamples handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSlaSamples } from "@rimcast/api-server/domains/telemetry/handlers";
import type { TelemetryDDDDependencies } from "@rimcast/api-server/domains/telemetry";
import { createSlaSample as createSlaSampleEntity } from "@rimcast/factories/telemetry";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@rimcast/tests/shared";
import { TELEMETRY_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSlaSamples", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TelemetryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TelemetryDDDDependencies>(
      TELEMETRY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSlaSampleEntity({ orgId }),
      createSlaSampleEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSlaSamples, "execute").mockResolvedValue(useCaseResult);

    await listSlaSamples(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSlaSamples.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
