/**
 * LatencyBudget Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { LatencyBudgetEntity } from "@rimcast/core/models/models/index.js";
import { modelsSchemas } from "@rimcast/core/models";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mdl";

export function createLatencyBudget(overrides: Partial<LatencyBudgetEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    allowCloudOverflow: overrides.allowCloudOverflow ?? faker.datatype.boolean(),
    maxLatencyMs: overrides.maxLatencyMs ?? faker.number.int(),
    modelVersionId: overrides.modelVersionId ?? `mdl_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return modelsSchemas.LatencyBudget.parse(raw);
}

export function latencyBudgetBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createLatencyBudget(overrides));
}
