/**
 * Placements DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Placements Domain Module - Composition root
 *
 * DDD: Composition root for placements domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PlacementRepositoryAdapter,
  RollbackRepositoryAdapter,
  SimulateRepositoryAdapter,
} from "@rimcast/adapters/placements";
import { getIdGeneratorService } from "@rimcast/adapters";
import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetPlacement,
  ExecuteListPlacements,
  ExecuteRequestPlacement,
  ExecuteRollbackPlacement,
  ExecuteSimulatePlacementFeasibility,
} from "@rimcast/services/placements/usecases";
// Ports (interfaces)
import type {
  PlacementRepository,
  RollbackRepository,
  SimulateRepository,
} from "@rimcast/services/placements/ports";

export interface PlacementsDomainModule {
  repos: {
    placements: PlacementRepository;
    rollbacks: RollbackRepository;
    simulates: SimulateRepository;
  };
  useCases: {
    placements: {
      get: ExecuteGetPlacement;
      list: ExecuteListPlacements;
      request: ExecuteRequestPlacement;
    };
    rollbacks: {
      get: ExecuteRollbackPlacement;
    };
    simulates: {
      get: ExecuteSimulatePlacementFeasibility;
    };
  };
}

export function buildPlacementsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PlacementsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      placements?: PlacementRepository;
      rollbacks?: RollbackRepository;
      simulates?: SimulateRepository;
    } = {};

    obj.placements = new PlacementRepositoryAdapter(dynamoClient);
    obj.rollbacks = new RollbackRepositoryAdapter(dynamoClient);
    obj.simulates = new SimulateRepositoryAdapter(dynamoClient);
    return {
      placements: obj.placements!,
      rollbacks: obj.rollbacks!,
      simulates: obj.simulates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    placements: {
      get: new ExecuteGetPlacement(executionContext, idGenerator, repos.placements),
      list: new ExecuteListPlacements(executionContext, idGenerator, repos.placements),
      request: new ExecuteRequestPlacement(executionContext, idGenerator, repos.placements),
    },
    rollbacks: {
      get: new ExecuteRollbackPlacement(executionContext, idGenerator, repos.rollbacks),
    },
    simulates: {
      get: new ExecuteSimulatePlacementFeasibility(executionContext, idGenerator, repos.simulates),
    },
  };
  return { repos, useCases: useCases as PlacementsDomainModule["useCases"] };
}
