/**
 * Capacity DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Capacity Domain Module - Composition root
 *
 * DDD: Composition root for capacity domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  NodeRepositoryAdapter,
  OfferRepositoryAdapter,
  WithdrawRepositoryAdapter,
} from "@rimcast/adapters/capacity";
import { getIdGeneratorService } from "@rimcast/adapters";
import type { AdapterDynamoDBClient } from "@rimcast/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListCapacityOffers,
  ExecuteListEdgeNodes,
  ExecutePublishCapacityOffer,
  ExecutePublishEdgeNode,
  ExecuteWithdrawCapacityOffer,
} from "@rimcast/services/capacity/usecases";
// Ports (interfaces)
import type {
  NodeRepository,
  OfferRepository,
  WithdrawRepository,
} from "@rimcast/services/capacity/ports";

export interface CapacityDomainModule {
  repos: {
    nodes: NodeRepository;
    offers: OfferRepository;
    withdraws: WithdrawRepository;
  };
  useCases: {
    nodes: {
      get: ExecutePublishEdgeNode;
      list: ExecuteListEdgeNodes;
    };
    offers: {
      get: ExecutePublishCapacityOffer;
      list: ExecuteListCapacityOffers;
    };
    withdraws: {
      get: ExecuteWithdrawCapacityOffer;
    };
  };
}

export function buildCapacityDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CapacityDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      nodes?: NodeRepository;
      offers?: OfferRepository;
      withdraws?: WithdrawRepository;
    } = {};

    obj.nodes = new NodeRepositoryAdapter(dynamoClient);
    obj.offers = new OfferRepositoryAdapter(dynamoClient);
    obj.withdraws = new WithdrawRepositoryAdapter(dynamoClient);
    return {
      nodes: obj.nodes!,
      offers: obj.offers!,
      withdraws: obj.withdraws!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    nodes: {
      get: new ExecutePublishEdgeNode(executionContext, idGenerator, repos.nodes),
      list: new ExecuteListEdgeNodes(executionContext, idGenerator, repos.nodes),
    },
    offers: {
      get: new ExecutePublishCapacityOffer(executionContext, idGenerator, repos.offers),
      list: new ExecuteListCapacityOffers(executionContext, idGenerator, repos.offers),
    },
    withdraws: {
      get: new ExecuteWithdrawCapacityOffer(executionContext, idGenerator, repos.withdraws),
    },
  };
  return { repos, useCases: useCases as CapacityDomainModule["useCases"] };
}
