/**
 * Routes for LatencyBudget
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { setLatencyBudget } from "../handlers/latency-budget.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function latencyBudgetRoutes(fastify: FastifyInstance) {
  // PUT /v1/models/{modelVersionId}/latency-budget (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/models/:modelVersionId/latency-budget",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getModelsDependenciesForRequest();
        await setLatencyBudget(request, reply, deps);
      });
    }
  );


}
