/**
 * EgressPolicy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EgressPolicyEntity } from "@rimcast/core/governance/models/index.js";
import { governanceSchemas } from "@rimcast/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createEgressPolicy(overrides: Partial<EgressPolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `egr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    allowOverflow: overrides.allowOverflow ?? faker.datatype.boolean(),
    purposeTags: overrides.purposeTags ?? [],
    siteId: overrides.siteId ?? faker.string.uuid(),
    ...overrides,
  };

  return governanceSchemas.EgressPolicy.parse(raw);
}

export function egressPolicyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEgressPolicy(overrides));
}
