/**
 * ListPlacement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPlacementsParams } from "@rimcast/core/placements";

export function createListPlacementRequest(overrides: Partial<ListPlacementsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
