/**
 * SetLatencyBudget handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { setLatencyBudget } from "@rimcast/api-server/domains/models/handlers";
import type { ModelsDDDDependencies } from "@rimcast/api-server/domains/models";
import { createLatencyBudget as createLatencyBudgetEntity } from "@rimcast/factories/models";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@rimcast/tests/shared";
import { MODELS_USE_CASES } from "../__factories__/use-cases.js";

describe("SetLatencyBudget", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelsDDDDependencies>(
      MODELS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createLatencyBudgetEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { modelVersionId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSetLatencyBudget, "execute").mockResolvedValue(useCaseResult);

    await setLatencyBudget(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSetLatencyBudget.execute).toHaveBeenCalledWith(expect.objectContaining({ modelVersionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
