/**
 * ClearRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClearRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ClearRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ClearRepository,
} from "@rimcast/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ClearRepositoryDdb } from "./clear-repository.ddb.js";

/**
 * ClearRepositoryAdapter
 *
 * Implements ClearRepository port for infrastructure layer.
 */
export class ClearRepositoryAdapter implements ClearRepository {
  private readonly ddb: ClearRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ClearRepositoryDdb(this.dynamoClient);
  }

  async clearSafeMode(input: Parameters<ClearRepository['clearSafeMode']>[0]): Promise<Awaited<ReturnType<ClearRepository['clearSafeMode']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.clearSafeMode(input);
  }
}
