/**
 * EgressPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EgressPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EgressPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EgressPolicyRepository,
} from "@rimcast/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EgressPolicyRepositoryDdb } from "./egress-policy-repository.ddb.js";

/**
 * EgressPolicyRepositoryAdapter
 *
 * Implements EgressPolicyRepository port for infrastructure layer.
 */
export class EgressPolicyRepositoryAdapter implements EgressPolicyRepository {
  private readonly ddb: EgressPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EgressPolicyRepositoryDdb(this.dynamoClient);
  }

  async upsertEgressPolicy(input: Parameters<EgressPolicyRepository['upsertEgressPolicy']>[0]): Promise<Awaited<ReturnType<EgressPolicyRepository['upsertEgressPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertEgressPolicy(input);
  }
}
