/**
 * OverflowExceptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverflowExceptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OverflowExceptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OverflowExceptionRepository,
} from "@rimcast/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OverflowExceptionRepositoryDdb } from "./overflow-exception-repository.ddb.js";

/**
 * OverflowExceptionRepositoryAdapter
 *
 * Implements OverflowExceptionRepository port for infrastructure layer.
 */
export class OverflowExceptionRepositoryAdapter implements OverflowExceptionRepository {
  private readonly ddb: OverflowExceptionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OverflowExceptionRepositoryDdb(this.dynamoClient);
  }

  async listOverflowExceptions(input: Parameters<OverflowExceptionRepository['listOverflowExceptions']>[0]): Promise<Awaited<ReturnType<OverflowExceptionRepository['listOverflowExceptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listOverflowExceptions(input);
  }

  async requestOverflowException(input: Parameters<OverflowExceptionRepository['requestOverflowException']>[0]): Promise<Awaited<ReturnType<OverflowExceptionRepository['requestOverflowException']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestOverflowException(input);
  }
}
