/**
 * SiteFreezeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SiteFreezeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SiteFreezeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SiteFreezeRepository,
} from "@rimcast/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SiteFreezeRepositoryDdb } from "./site-freeze-repository.ddb.js";

/**
 * SiteFreezeRepositoryAdapter
 *
 * Implements SiteFreezeRepository port for infrastructure layer.
 */
export class SiteFreezeRepositoryAdapter implements SiteFreezeRepository {
  private readonly ddb: SiteFreezeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SiteFreezeRepositoryDdb(this.dynamoClient);
  }

  async listSiteFreezes(input: Parameters<SiteFreezeRepository['listSiteFreezes']>[0]): Promise<Awaited<ReturnType<SiteFreezeRepository['listSiteFreezes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSiteFreezes(input);
  }

  async freezeSitePlacements(input: Parameters<SiteFreezeRepository['freezeSitePlacements']>[0]): Promise<Awaited<ReturnType<SiteFreezeRepository['freezeSitePlacements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.freezeSitePlacements(input);
  }
}
