/**
 * UnfreezeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UnfreezeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements UnfreezeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  UnfreezeRepository,
} from "@rimcast/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { UnfreezeRepositoryDdb } from "./unfreeze-repository.ddb.js";

/**
 * UnfreezeRepositoryAdapter
 *
 * Implements UnfreezeRepository port for infrastructure layer.
 */
export class UnfreezeRepositoryAdapter implements UnfreezeRepository {
  private readonly ddb: UnfreezeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new UnfreezeRepositoryDdb(this.dynamoClient);
  }

  async unfreezeSitePlacements(input: Parameters<UnfreezeRepository['unfreezeSitePlacements']>[0]): Promise<Awaited<ReturnType<UnfreezeRepository['unfreezeSitePlacements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.unfreezeSitePlacements(input);
  }
}
