/**
 * SiteFreeze Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SiteFreezeEntity } from "@rimcast/core/governance/models/index.js";
import { governanceSchemas } from "@rimcast/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createSiteFreeze(overrides: Partial<SiteFreezeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `frz_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    active: overrides.active ?? faker.datatype.boolean(),
    siteId: overrides.siteId ?? faker.string.uuid(),
    ...overrides,
  };

  return governanceSchemas.SiteFreeze.parse(raw);
}

export function siteFreezeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSiteFreeze(overrides));
}
