/**
 * Handlers for VModel
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelsDomainModule } from "../dependencies/models-ddd.dependencies.js";
import type { GetModelVersionInput, ListModelVersionsInput, RegisterModelVersionInput } from "@rimcast/services/models";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/models
 * Operation: listModelVersions
 */
export async function listModelVersions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListModelVersionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.vModels.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/models
 * Operation: registerModelVersion
 */
export async function registerModelVersion(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterModelVersionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vModels.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/models/{modelVersionId}
 * Operation: getModelVersion
 */
export async function getModelVersion(
  request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetModelVersionInput = {
    modelVersionId: request.params.modelVersionId,
  };
  const result = await deps.useCases.vModels.get.execute(input);
  return reply.code(200).send(result);
}


