/**
 * ListOffer DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListCapacityOffersParams } from "@rimcast/core/capacity";

export function createListOfferRequest(overrides: Partial<ListCapacityOffersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
