/**
 * Placement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Placement DTOs
 *
 * DDD: Application DTOs for Placement use cases.
 */

import type { GetPlacementParams, ListPlacementsParams, RequestPlacementRequestInput } from "@rimcast/core/placements/types";

export type ListPlacementsInput = ListPlacementsParams;

export type RequestPlacementInput = RequestPlacementRequestInput;

export type GetPlacementInput = GetPlacementParams;

export type ListPlacementsOutput = {};

export type RequestPlacementOutput = {};

export type GetPlacementOutput = {};
