/**
 * Simulate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: placements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Simulate DTOs
 *
 * DDD: Application DTOs for Simulate use cases.
 */

import type { SimulatePlacementFeasibilityRequestInput } from "@rimcast/core/placements/types";

export type SimulatePlacementFeasibilityInput = SimulatePlacementFeasibilityRequestInput;

export type SimulatePlacementFeasibilityOutput = {};
